# 01. setup title with the name of the site
site_name: OpenNotesHub

# 02. setup logo, icon, format, etc.
theme:
  favicon: octicons/book-24
  palette:
    primary: blue grey
    accent: red
  
  font:
    text: Roboto
    code: Roboto Mono
    
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
    logo: octicons/book-16
  features:
    - content.code.annotate 
    - content.footnote.tooltips
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - navigation.top
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking

repo_name: nthaihoc/open-notes-hub
repo_url: https://github.com/nthaihoc/open-notes-hub

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js  
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# 03. setup markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - md_in_html
  - attr_list
  - footnotes
  - meta
  - toc:
      title: Table of Contents
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark 
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.blocks.definition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - macros
  - search

copyright: ©️ 2025 by Thai Hoc Nguyen

# 04. setup navigation
nav:
  - Home: index.md

  - Research Logs: 
    - Research Logs: research/README.md

    - Cervical Cancer Cytology:
      - Cervical Cancer Cytology: research/cervical-cancer-cytology/README.md
      - Experiment 01. Data Aggeration Training Evaluation : research/cervical-cancer-cytology/experiments/exp-01-ensemble_learning.md 
      - Experiment 02. Self Supervised Learning: research/cervical-cancer-cytology/experiments/exp-02-self_supervised_learning.md

    # - Pronunciation Scoring:
    #   - Overview: research/pronunciation-scoring/README.md
    #   - Report 01 - Introduction: research/pronunciation-scoring/experiments/report01.md
    #   - Report 02 - Baseline Models & Error Analysis: research/pronunciation-scoring/experiments/report02.md

  - Course Notes:
    - Course Notes: courses/README.md

    - Applied Machine Learning: courses/applied-machine-learning/README.md

    - Large Language Models:
      - Large Language Models: courses/large-language-models/README.md
      - Lesson 03. Attention Mechanisms: courses/large-language-models/lesson-03-attention_mechanisms_knowledge_base.md
      
  - Knowledge Base:
    - Knowledge Base: knowledge-base/README.md

    # - MLOps Tutorials: knowledge-base/mlops-tutorials/README.md
    - FastAPI Tutorials:
      - FastAPI Tutorials: knowledge-base/fastapi-tutorials/README.md
      - Lesson 01. FastAPI Overview and Project Setup: knowledge-base/fastapi-tutorials/lesson-01-fastapi_overview_and_project_setup.md

# 05. setup other configurations
extra:
  social:
    - icon: material/school
      link: https://ictu.edu.vn
      name: Thai Nguyen University of Information and Technology Communication
    - icon: material/domain
      link: https://iast.ictu.edu.vn
      name: Institute of Applied Science Technology
    - icon: material/web
      link: https://nthaihoc.github.io/about-me
      name: Profile
    - icon: material/email-multiple-outline
      link: mailto:thaihoc.ictu@gmail.com
      name: Email
    - icon: material/github
      link: https://github.com/nthaihoc?tab=repositories
      name: Github
    - icon: material/facebook
      link: https://www.facebook.com/nthaihoc.02
      name: Facebook
      