# 01. setup title with the name of the site
site_name: OpenNotesHub

# 02. setup logo, icon, format, etc.
theme:
  favicon: assets/images/logo.png
  palette:
    primary: black
    accent: red
  
  font:
    text: Roboto
    code: Roboto Mono
    
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
  logo: assets/images/logo.png
  features:
    - content.code.annotate 
    - content.footnote.tooltips
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - navigation.top
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking

repo_name: nthaihoc/open-notes-hub
repo_url: https://github.com/nthaihoc/open-notes-hub

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js  
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# 03. setup markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - md_in_html
  - attr_list
  - footnotes
  - meta
  - toc:
      title: Mục Lục
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark 
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.blocks.definition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - macros
  - search

copyright: ©️ 2025 by Thai Hoc Nguyen

# 04. setup navigation
nav:
  - Home: index.md

  - Research Logs: 
    - Research Logs: research-logs/README.md
    - Cervical Cancer Cytology: 
      - Cervical Cancer Cytology: research-logs/cervical-cancer-cytology/README.md
      - Self-Supervised Learining Paper Design Notes: research-logs/cervical-cancer-cytology/ssl_paper_design.md
    - Pronunciation Scoring:
      - Pronunciation Scoring: research-logs/pronunciation-scoring/README.md
      - Tổng quan về Pronunciation Scoring: research-logs/pronunciation-scoring/report01.md
      - Triển khai mô hình cơ bản, đánh giá và phân tích lỗi: research-logs/pronunciation-scoring/report02.md


  - Course Notes:
    - Course Notes: course-notes/README.md
    - Applied Machine Learning: course-notes/applied-machine-learning/README.md

  - Knowledge Base:
    - Knowledge Base: knowledge-base/README.md
    - English Knowledge Base: research-logs/cervical-cancer-cytology.md

# 05. setup other configurations
extra:
  social:
    - icon: octicons/mail-16
      link: mailto:<thaihocit02@gmail.com>
      name: Email
    - icon: material/web
      link: https://nthaihoc.github.io/about-me
      name: Author
    - icon: simple/workplace
      link: https://iast.ictu.edu.vn
      name: Institute of Applied Science Technology
  analytics:
    provider: google
    property: UA-XXXXXXXX-X  