# 01. setup title with the name of the site
site_name: OpenNotesHub

theme:
  logo: assets/logos/logo.png
  favicon: octicons/book-24
  palette:
    scheme: default
    primary: black
    accent: red
  
  font:
    text: Roboto
    code: Roboto Mono
    
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github

  features:
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - navigation.top
    - navigation.footer
    - navigation.instant.preview
    - navigation.tracking

repo_name: nthaihoc/open-notes-hub
repo_url: https://github.com/nthaihoc/open-notes-hub

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  # - javascripts/mathjax.js  
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# 03. setup markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - md_in_html
  - attr_list
  - footnotes
  - meta
  - toc:
      title: Table of Contents
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark 
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.blocks.definition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji  
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
  - tables
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - macros
  - search
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true
      enable_git_follow: false 

  - git-committers:
      repository: nthaihoc/open-notes-hub
      branch: main
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY

copyright: ©️ 2025 by Thai-Hoc Nguyen

# 04. setup navigation
nav:
  - Home: index.md

  - Research Logs:
    - Introduction: research/README.md
    
    - Pronunciation Scoring:
      - Overview: research/pronunciation-scoring/README.md
      - Report 01 - Introduction: research/pronunciation-scoring/experiments/01-ssl_for_pronscore.md
      - Report 02 - Baseline Models & Error Analysis: research/pronunciation-scoring/literature-review/related_work.md

  - Course Notes:
    - Course Notes: courses/README.md

    - Applied Machine Learning: courses/applied-machine-learning/README.md

    - Large Language Models:
      - Large Language Models: courses/large-language-models/README.md
      - Lesson 03. Attention Mechanisms: courses/large-language-models/lessson/lesson-03-attention_mechanisms.md
      
  - Knowledge Base:
    - Knowledge Base: knowledge-base/README.md

    # - MLOps Tutorials: knowledge-base/mlops-tutorials/README.md
    - FastAPI Tutorials:
      - FastAPI Tutorials: knowledge-base/fastapi/README.md
      - Lesson 01. FastAPI Overview and Project Setup: knowledge-base/fastapi/lesson-01-overview.md
    
    - Interview AI:
      - Cheetsheat AI for VinUI: knowledge-base/interview-ai/interview_vinui.md

  # - IAI Lab:
  #   - IAI Lab: iai-lab/README.md
  #   - Operational Framework: iai-lab/tracks.md
  #   - Guidelines: iai-lab/guidelines.md

  # - Resources:
  #   - Overview: resources/README.md

# 05. setup other configurations
extra:
  social:
    - icon: material/school
      link: https://ictu.edu.vn
      name: Thai Nguyen University of Information and Technology Communication
    - icon: material/domain
      link: https://iast.ictu.edu.vn
      name: Institute of Applied Science Technology
    - icon: material/web
      link: https://nthaihoc.github.io/about-me
      name: Profile
    - icon: material/email-multiple-outline
      link: mailto:thaihoc.ictu@gmail.com
      name: Email
    - icon: material/github
      link: https://github.com/nthaihoc?tab=repositories
      name: Github
    - icon: material/facebook
      link: https://www.facebook.com/nthaihoc.02
      name: Facebook
      